import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { NextAuthProvider } from "@/components/providers/provider";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <NextAuthProvider>
        <body
          className={`${inter.className} h-screen w-screen flex bg-gradient-to-t from-slate-700 to-violet-950`}
        >
          {children}
        </body>
      </NextAuthProvider>
    </html>
  );
}
